VECTOR SPACE MODEL

Answer Retrieval using COSINE SIMILARITY

In [1]:
import nltk
import numpy as np
import random
import pandas as pd
import string

In [2]:
#lOAD THE DATA
file = pd.read_csv("C:\\Users\\pondh\\Desktop\\data\\int_classification1.csv", engine='python')

In [3]:
file.head()

Service Type           Intent                                Question  \
0      CreditCard  new_credit_card         How do I get a new credit card?   
1      CreditCard  new_credit_card        How can I get a new credit card?   
2      CreditCard  new_credit_card               I want a new credit card?   
3      CreditCard  new_credit_card  How can I apply for a new credit card?   
4      CreditCard  new_credit_card  I want to apply for a new credit card?   

                                              Answer  
0  To apply for a new credit card, please visit h...  
1  To apply for a new credit card, please visit h...  
2  To apply for a new credit card, please visit h...  
3  To apply for a new credit card, please visit h...  
4  To apply for a new credit card, please visit h...

In [4]:
data = file.loc[:,['Question','Answer']]

In [5]:
data.shape

(860, 2)

In [6]:
data.head()

Question  \
0         How do I get a new credit card?   
1        How can I get a new credit card?   
2               I want a new credit card?   
3  How can I apply for a new credit card?   
4  I want to apply for a new credit card?   

                                              Answer  
0  To apply for a new credit card, please visit h...  
1  To apply for a new credit card, please visit h...  
2  To apply for a new credit card, please visit h...  
3  To apply for a new credit card, please visit h...  
4  To apply for a new credit card, please visit h...

In [7]:
list1 = data['Question'].values.tolist()

In [8]:
list2 = data['Answer'].values.tolist()

In [9]:
#Strip the records and create a word list
word_list1 = []
for record in (list1):
    #print(record[0])
    words = []
    tokens = record.split()
    print(tokens)
    for token in tokens:
        words.append(token.lower())
    word_list1.append(words)

['How', 'do', 'I', 'get', 'a', 'new', 'credit', 'card?']
['How', 'can', 'I', 'get', 'a', 'new', 'credit', 'card?']
['I', 'want', 'a', 'new', 'credit', 'card?']
['How', 'can', 'I', 'apply', 'for', 'a', 'new', 'credit', 'card?']
['I', 'want', 'to', 'apply', 'for', 'a', 'new', 'credit', 'card?']
['I', 'want', 'to', 'get', 'a', 'new', 'creidt', 'card?']
['Can', 'you', 'get', 'me', 'a', 'new', 'credit', 'card?']
['How', 'can', 'I', 'get', 'myself', 'a', 'new', 'credit', 'card?']
['Can', 'I', 'apply', 'for', 'a', 'new', 'credit', 'card?']
['Can', 'you', 'help', 'me', 'get', 'a', 'new', 'credit', 'card?']
['What', 'documents', 'are', 'required', 'for', 'applying', 'for', 'a', 'new', 'credit', 'card?']
['What', 'documents', 'do', 'you', 'need', 'to', 'give', 'me', 'a', 'new', 'credit', 'card?']
['Can', 'you', 'tell', 'me', 'what', 'documents', 'are', 'needed', 'to', 'give', 'me', 'a', 'new', 'credit', 'card?']
['Can', 'you', 'give', 'me', 'the', 'list', 'of', 'documents', 'required', 'to', 'ge

In [10]:
#Strip the records and create a word list
word_list2 = []
for record in (list2):
    #print(record[0])
    words = []
    tokens = record.split()
    print(tokens)
    for token in tokens:
        words.append(token.lower())
    word_list2.append(words)

['To', 'apply', 'for', 'a', 'new', 'credit', 'card,', 'please', 'visit', 'http://vwxyzcom/credit-card/apply', 'or', 'call', 'The', 'VWXYZ', 'Bank', '24-Hour', 'Customer', 'Care', 'Centre', 'at', '1800-XXX-XXXX', 'or', 'visit', 'the', 'nearest', 'brach', 'at', 'http://vwxyzcom/branches.']
['To', 'apply', 'for', 'a', 'new', 'credit', 'card,', 'please', 'visit', 'http://vwxyzcom/credit-card/apply', 'or', 'call', 'The', 'VWXYZ', 'Bank', '24-Hour', 'Customer', 'Care', 'Centre', 'at', '1800-XXX-XXXX', 'or', 'visit', 'the', 'nearest', 'brach', 'at', 'http://vwxyzcom/branches.']
['To', 'apply', 'for', 'a', 'new', 'credit', 'card,', 'please', 'visit', 'http://vwxyzcom/credit-card/apply', 'or', 'call', 'The', 'VWXYZ', 'Bank', '24-Hour', 'Customer', 'Care', 'Centre', 'at', '1800-XXX-XXXX', 'or', 'visit', 'the', 'nearest', 'brach', 'at', 'http://vwxyzcom/branches.']
['To', 'apply', 'for', 'a', 'new', 'credit', 'card,', 'please', 'visit', 'http://vwxyzcom/credit-card/apply', 'or', 'call', 'The', 'V

In [11]:
string1 = str(word_list1)

In [12]:
string2 = str(word_list2)

In [13]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\pondh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [14]:
word_tokens1 = nltk.word_tokenize(string1)

In [15]:
word_tokens2 = nltk.word_tokenize(string2)

In [16]:
nltk.download('wordnet')
lemmer = nltk.stem.WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\pondh\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [17]:
string.punctuation1 = '!"#$%&\'()*+,-/:;<=>.@[\\]^_`{|}~'

In [18]:
#LEMMATIZE
def LemTokens(tokens):
    return [lemmer.lemmatize(token) for token in tokens]
#REMOVE PUNCTUATION
#NORMALIZE
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation1)
def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

In [19]:
QuestionSet = LemNormalize(string1)
QuestionSet = LemTokens(QuestionSet)

In [20]:
def multi_split(s, seprators):
    buf = [s]
    for sep in seprators:
        for loop, text in enumerate(buf):
            buf[loop:loop+1] = [i for i in text.split(sep) if i]
    return buf

In [21]:
QuestionSet1 = str(QuestionSet)
QuestionSet2 = multi_split(QuestionSet1, '?')

In [22]:
string.punctuation2 = '!"#$%&\'()*+,-/:;<=>@[\\]^_`{|}~?'

In [23]:
def LemTokens(tokens):
    return [lemmer.lemmatize(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation2)
def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

In [24]:
AnswerSet = LemNormalize(string2)
AnswerSet = LemTokens(AnswerSet)

In [25]:
AnswerSet1 = str(AnswerSet)
AnswerSet2 = multi_split(AnswerSet1, '.')

In [26]:
len(QuestionSet2)

861

In [27]:
QuestionSet2[859]

"', 'i', 'want', 'to', 'know', 'what', 'will', 'happen', 'if', 'there', 'are', 'no', 'transaction', 'in', 'my', 'account', '"

In [28]:
len(AnswerSet2)

861

In [29]:
AnswerSet2[859]

"', 'if', 'no', 'salary', 'is', 'credited', 'in', 'the', 'account', 'or', 'there', 'are', 'no', 'transaction', 'in', 'the', 'account', 'for', '6', 'consecutive', 'month', 'vwxyz', 'bank', 'shall', 'be', 'entitled', 'to', 'treat', 'the', 'salary', 'account', 'a', 'a', 'regular', 'salary', 'account', 'without', 'any', 'intimation', 'to', 'the', 'customer', 'and', 'the', 'customer', 'shall', 'be', 'bound', 'to', 'maintain', 'a', 'minimum', 'monthly', 'average', 'balance', 'mab', 'of', 'r', '10000', 'from', 'the', 'date', 'of', 'change', 'of', 'the', 'status', '"

In [30]:
data['tidyquestion'] = QuestionSet2[0:860]

In [31]:
data['tidyanswer'] = AnswerSet2[0:860]

In [32]:
data.head()

Question  \
0         How do I get a new credit card?   
1        How can I get a new credit card?   
2               I want a new credit card?   
3  How can I apply for a new credit card?   
4  I want to apply for a new credit card?   

                                              Answer  \
0  To apply for a new credit card, please visit h...   
1  To apply for a new credit card, please visit h...   
2  To apply for a new credit card, please visit h...   
3  To apply for a new credit card, please visit h...   
4  To apply for a new credit card, please visit h...   

                                        tidyquestion  \
0  ['how', 'do', 'i', 'get', 'a', 'new', 'credit'...   
1  ', 'how', 'can', 'i', 'get', 'a', 'new', 'cred...   
2    ', 'i', 'want', 'a', 'new', 'credit', 'card', '   
3  ', 'how', 'can', 'i', 'apply', 'for', 'a', 'ne...   
4  ', 'i', 'want', 'to', 'apply', 'for', 'a', 'ne...   

                                          tidyanswer  
0  ['to', 'apply', 'for', 'a', 'new', 'credit', '...  
1  ', 'to', 'apply', 'for', 'a', 'new', 'credit',...  
2  ', 'to', 'apply', 'for', 'a', 'new', 'credit',...  
3  ', 'to', 'apply', 'for', 'a', 'new', 'credit',...  
4  ', 'to', 'apply', 'for', 'a', 'new', 'credit',...

In [33]:
data.tail()

Question  \
855  What will happen to my  account If there are n...   
856          There are no transactions in my  account?   
857  What should I do if there are no transactions ...   
858  I want to know what will happen if there are n...   
859  I want to know what will happen if there are n...   

                                                Answer  \
855  If no salary is credited in the account or the...   
856  If no salary is credited in the account or the...   
857  If no salary is credited in the account or the...   
858  If no salary is credited in the account or the...   
859  If no salary is credited in the account or the...   

                                          tidyquestion  \
855  ', 'what', 'will', 'happen', 'to', 'my', 'acco...   
856  ', 'there', 'are', 'no', 'transaction', 'in', ...   
857  ', 'what', 'should', 'i', 'do', 'if', 'there',...   
858  ', 'i', 'want', 'to', 'know', 'what', 'will', ...   
859  ', 'i', 'want', 'to', 'know', 'what', 'will', ...   

                                            tidyanswer  
855  ', 'if', 'no', 'salary', 'is', 'credited', 'in...  
856  ', 'if', 'no', 'salary', 'is', 'credited', 'in...  
857  ', 'if', 'no', 'salary', 'is', 'credited', 'in...  
858  ', 'if', 'no', 'salary', 'is', 'credited', 'in...  
859  ', 'if', 'no', 'salary', 'is', 'credited', 'in...

In [34]:
#COUNT VECTORIZER
from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer(max_df=0.90, min_df=2, max_features=1000, stop_words='english')

In [35]:
CV2 = count_vectorizer.fit_transform(data['tidyanswer'])

In [36]:
CV1 = count_vectorizer.transform(data['tidyquestion'])

In [37]:
CV1[1]

<1x463 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [38]:
CV2[1]

<1x463 sparse matrix of type '<class 'numpy.int64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [39]:
print(CV1.shape)

(860, 463)


In [40]:
print(CV2.shape)

(860, 463)


In [43]:
print(count_vectorizer.vocabulary_)

{'apply': 36, 'new': 283, 'credit': 110, 'card': 72, 'visit': 445, 'httpvwxyzcomcreditcardapply': 198, 'vwxyz': 449, 'bank': 53, '24hour': 8, 'customer': 118, 'care': 73, 'centre': 79, '1800xxxxxxx': 4, 'nearest': 279, 'brach': 62, 'httpvwxyzcombranches': 197, 'document': 140, 'required': 374, 'applying': 37, '1identitiy': 5, 'proof': 338, 'pan': 305, 'passport': 308, 'voter': 448, 'aadhar': 13, 'address': 22, 'driving': 145, 'license': 241, 'electricity': 150, 'size': 401, 'photograph': 318, 'eligibility': 151, 'criterion': 113, 'crdit': 109, 'minimum': 275, 'score': 393, '750': 11, 'age': 25, 'group': 190, '2565': 9, 'year': 461, 'existing': 166, 'transferable': 433, 'usage': 439, 'subject': 413, 'term': 422, 'mentioned': 272, 'time': 428, 'internationally': 220, 'valid': 442, 'issued': 226, 'member': 270, 'worldwide': 455, 'payment': 311, 'foreign': 179, 'exchange': 164, 'merchant': 273, 'establishment': 159, 'nepal': 280, 'bhutan': 58, 'restricted': 380, 'india': 213, 'outside': 29

In [45]:
#TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_df=0.90, min_df=2, max_features=1000, stop_words='english')

In [46]:
tfidf2 = tfidf_vectorizer.fit_transform(data['tidyanswer'])

In [47]:
tfidf1 = tfidf_vectorizer.transform(data['tidyquestion'])

In [48]:
tfidf1[0]

<1x463 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [49]:
tfidf2[1]

<1x463 sparse matrix of type '<class 'numpy.float64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [50]:
print(tfidf1.shape)

(860, 463)


In [51]:
print(tfidf2.shape)

(860, 463)


In [52]:
print(tfidf_vectorizer.vocabulary_)

{'apply': 36, 'new': 283, 'credit': 110, 'card': 72, 'visit': 445, 'httpvwxyzcomcreditcardapply': 198, 'vwxyz': 449, 'bank': 53, '24hour': 8, 'customer': 118, 'care': 73, 'centre': 79, '1800xxxxxxx': 4, 'nearest': 279, 'brach': 62, 'httpvwxyzcombranches': 197, 'document': 140, 'required': 374, 'applying': 37, '1identitiy': 5, 'proof': 338, 'pan': 305, 'passport': 308, 'voter': 448, 'aadhar': 13, 'address': 22, 'driving': 145, 'license': 241, 'electricity': 150, 'size': 401, 'photograph': 318, 'eligibility': 151, 'criterion': 113, 'crdit': 109, 'minimum': 275, 'score': 393, '750': 11, 'age': 25, 'group': 190, '2565': 9, 'year': 461, 'existing': 166, 'transferable': 433, 'usage': 439, 'subject': 413, 'term': 422, 'mentioned': 272, 'time': 428, 'internationally': 220, 'valid': 442, 'issued': 226, 'member': 270, 'worldwide': 455, 'payment': 311, 'foreign': 179, 'exchange': 164, 'merchant': 273, 'establishment': 159, 'nepal': 280, 'bhutan': 58, 'restricted': 380, 'india': 213, 'outside': 29

In [44]:
from sklearn.metrics.pairwise import cosine_similarity

In [45]:
type(CV2)

scipy.sparse.csr.csr_matrix

In [46]:
type(tfidf1)

scipy.sparse.csr.csr_matrix

In [47]:
vals1 = cosine_similarity(tfidf1, tfidf2)

In [48]:
vals1[0]

array([0.28323011, 0.28323011, 0.28323011, 0.28323011, 0.28323011,
       0.28323011, 0.28323011, 0.28323011, 0.28323011, 0.28323011,
       0.26409348, 0.26409348, 0.26409348, 0.26409348, 0.26409348,
       0.26409348, 0.26409348, 0.26409348, 0.26409348, 0.26409348,
       0.1250747 , 0.1250747 , 0.1250747 , 0.1250747 , 0.1250747 ,
       0.1250747 , 0.1250747 , 0.1250747 , 0.1250747 , 0.1250747 ,
       0.16543098, 0.16543098, 0.16543098, 0.16543098, 0.16543098,
       0.16543098, 0.16543098, 0.16543098, 0.16543098, 0.16543098,
       0.06919581, 0.06919581, 0.06919581, 0.06919581, 0.06919581,
       0.06919581, 0.06919581, 0.06919581, 0.06919581, 0.06919581,
       0.06919581, 0.06919581, 0.06919581, 0.06919581, 0.18433529,
       0.18433529, 0.18433529, 0.18433529, 0.18433529, 0.18433529,
       0.18433529, 0.18433529, 0.18433529, 0.18433529, 0.18433529,
       0.18433529, 0.18433529, 0.18433529, 0.03705382, 0.03705382,
       0.03705382, 0.03705382, 0.03705382, 0.03705382, 0.03705

In [49]:
vals1[1]

array([0.28323011, 0.28323011, 0.28323011, 0.28323011, 0.28323011,
       0.28323011, 0.28323011, 0.28323011, 0.28323011, 0.28323011,
       0.26409348, 0.26409348, 0.26409348, 0.26409348, 0.26409348,
       0.26409348, 0.26409348, 0.26409348, 0.26409348, 0.26409348,
       0.1250747 , 0.1250747 , 0.1250747 , 0.1250747 , 0.1250747 ,
       0.1250747 , 0.1250747 , 0.1250747 , 0.1250747 , 0.1250747 ,
       0.16543098, 0.16543098, 0.16543098, 0.16543098, 0.16543098,
       0.16543098, 0.16543098, 0.16543098, 0.16543098, 0.16543098,
       0.06919581, 0.06919581, 0.06919581, 0.06919581, 0.06919581,
       0.06919581, 0.06919581, 0.06919581, 0.06919581, 0.06919581,
       0.06919581, 0.06919581, 0.06919581, 0.06919581, 0.18433529,
       0.18433529, 0.18433529, 0.18433529, 0.18433529, 0.18433529,
       0.18433529, 0.18433529, 0.18433529, 0.18433529, 0.18433529,
       0.18433529, 0.18433529, 0.18433529, 0.03705382, 0.03705382,
       0.03705382, 0.03705382, 0.03705382, 0.03705382, 0.03705

In [50]:
vals1[11]

array([0.22527059, 0.22527059, 0.22527059, 0.22527059, 0.22527059,
       0.22527059, 0.22527059, 0.22527059, 0.22527059, 0.22527059,
       0.30925585, 0.30925585, 0.30925585, 0.30925585, 0.30925585,
       0.30925585, 0.30925585, 0.30925585, 0.30925585, 0.30925585,
       0.09947972, 0.09947972, 0.09947972, 0.09947972, 0.09947972,
       0.09947972, 0.09947972, 0.09947972, 0.09947972, 0.09947972,
       0.13157759, 0.13157759, 0.13157759, 0.13157759, 0.13157759,
       0.13157759, 0.13157759, 0.13157759, 0.13157759, 0.13157759,
       0.05503575, 0.05503575, 0.05503575, 0.05503575, 0.05503575,
       0.05503575, 0.05503575, 0.05503575, 0.05503575, 0.05503575,
       0.05503575, 0.05503575, 0.05503575, 0.05503575, 0.14661336,
       0.14661336, 0.14661336, 0.14661336, 0.14661336, 0.14661336,
       0.14661336, 0.14661336, 0.14661336, 0.14661336, 0.14661336,
       0.14661336, 0.14661336, 0.14661336, 0.02947122, 0.02947122,
       0.02947122, 0.02947122, 0.02947122, 0.02947122, 0.02947

In [51]:
vals2 = cosine_similarity(CV1, CV2)

In [52]:
type(vals2)

numpy.ndarray

In [53]:
vals2.shape

(860, 860)

In [54]:
vals2[0]

array([0.39735971, 0.39735971, 0.39735971, 0.39735971, 0.39735971,
       0.39735971, 0.39735971, 0.39735971, 0.39735971, 0.39735971,
       0.48795004, 0.48795004, 0.48795004, 0.48795004, 0.48795004,
       0.48795004, 0.48795004, 0.48795004, 0.48795004, 0.48795004,
       0.2981424 , 0.2981424 , 0.2981424 , 0.2981424 , 0.2981424 ,
       0.2981424 , 0.2981424 , 0.2981424 , 0.2981424 , 0.2981424 ,
       0.32025631, 0.32025631, 0.32025631, 0.32025631, 0.32025631,
       0.32025631, 0.32025631, 0.32025631, 0.32025631, 0.32025631,
       0.26490647, 0.26490647, 0.26490647, 0.26490647, 0.26490647,
       0.26490647, 0.26490647, 0.26490647, 0.26490647, 0.26490647,
       0.26490647, 0.26490647, 0.26490647, 0.26490647, 0.39605902,
       0.39605902, 0.39605902, 0.39605902, 0.39605902, 0.39605902,
       0.39605902, 0.39605902, 0.39605902, 0.39605902, 0.39605902,
       0.39605902, 0.39605902, 0.39605902, 0.17407766, 0.17407766,
       0.17407766, 0.17407766, 0.17407766, 0.17407766, 0.17407

In [55]:
vals2[1]

array([0.39735971, 0.39735971, 0.39735971, 0.39735971, 0.39735971,
       0.39735971, 0.39735971, 0.39735971, 0.39735971, 0.39735971,
       0.48795004, 0.48795004, 0.48795004, 0.48795004, 0.48795004,
       0.48795004, 0.48795004, 0.48795004, 0.48795004, 0.48795004,
       0.2981424 , 0.2981424 , 0.2981424 , 0.2981424 , 0.2981424 ,
       0.2981424 , 0.2981424 , 0.2981424 , 0.2981424 , 0.2981424 ,
       0.32025631, 0.32025631, 0.32025631, 0.32025631, 0.32025631,
       0.32025631, 0.32025631, 0.32025631, 0.32025631, 0.32025631,
       0.26490647, 0.26490647, 0.26490647, 0.26490647, 0.26490647,
       0.26490647, 0.26490647, 0.26490647, 0.26490647, 0.26490647,
       0.26490647, 0.26490647, 0.26490647, 0.26490647, 0.39605902,
       0.39605902, 0.39605902, 0.39605902, 0.39605902, 0.39605902,
       0.39605902, 0.39605902, 0.39605902, 0.39605902, 0.39605902,
       0.39605902, 0.39605902, 0.39605902, 0.17407766, 0.17407766,
       0.17407766, 0.17407766, 0.17407766, 0.17407766, 0.17407

In [56]:
vals2[11]

array([0.3441236 , 0.3441236 , 0.3441236 , 0.3441236 , 0.3441236 ,
       0.3441236 , 0.3441236 , 0.3441236 , 0.3441236 , 0.3441236 ,
       0.50709255, 0.50709255, 0.50709255, 0.50709255, 0.50709255,
       0.50709255, 0.50709255, 0.50709255, 0.50709255, 0.50709255,
       0.25819889, 0.25819889, 0.25819889, 0.25819889, 0.25819889,
       0.25819889, 0.25819889, 0.25819889, 0.25819889, 0.25819889,
       0.2773501 , 0.2773501 , 0.2773501 , 0.2773501 , 0.2773501 ,
       0.2773501 , 0.2773501 , 0.2773501 , 0.2773501 , 0.2773501 ,
       0.22941573, 0.22941573, 0.22941573, 0.22941573, 0.22941573,
       0.22941573, 0.22941573, 0.22941573, 0.22941573, 0.22941573,
       0.22941573, 0.22941573, 0.22941573, 0.22941573, 0.34299717,
       0.34299717, 0.34299717, 0.34299717, 0.34299717, 0.34299717,
       0.34299717, 0.34299717, 0.34299717, 0.34299717, 0.34299717,
       0.34299717, 0.34299717, 0.34299717, 0.15075567, 0.15075567,
       0.15075567, 0.15075567, 0.15075567, 0.15075567, 0.15075

In [ ]:
stop

#CHATBOT

In [1]:
#ANSWER CORPUS with unique answers
text_file = open("C:\\Users\\pondh\\Desktop\\data\\answercorpus.txt", "r")
answers = text_file.readlines()

In [2]:
answers

['To apply for a new credit card, please visit http://vwxyzcom/credit-card/apply or call The VWXYZ Bank 24-Hour Customer Care Centre at 1800-XXX-XXXX or visit the nearest brach at http://vwxyzcom/branches.\n',
 'To apply for a new credit card, please visit http://vwxyzcom/credit-card/apply or call The VWXYZ Bank 24-Hour Customer Care Centre at 1800-XXX-XXXX or visit the nearest brach at http://vwxyzcom/branches.\n',
 'To apply for a new credit card, please visit http://vwxyzcom/credit-card/apply or call The VWXYZ Bank 24-Hour Customer Care Centre at 1800-XXX-XXXX or visit the nearest brach at http://vwxyzcom/branches.\n',
 'Below documents are required for applying for a new credit card: 1)Identitiy proof - PAN Card, Passport, Voter, Aadhar 2) Address Proof - Driving License, Electricity Bill, Aadhar Card 3) passport size photograph.\n',
 'Below documents are required for applying for a new credit card: 1)Identitiy proof - PAN Card, Passport, Voter, Aadhar 2) Address Proof - Driving Li

In [3]:
answersstr = str(answers)

In [4]:
from nltk.tokenize import sent_tokenize
sent_tokens = sent_tokenize(answersstr)

In [5]:
def multi_split(s, seprators):
    buf = [s]
    for sep in seprators:
        for loop, text in enumerate(buf):
            buf[loop:loop+1] = [i for i in text.split(sep) if i]
    return buf

In [6]:
sent_tokens = multi_split(answersstr, '.')

In [7]:
sent_tokens

["['To apply for a new credit card, please visit http://vwxyzcom/credit-card/apply or call The VWXYZ Bank 24-Hour Customer Care Centre at 1800-XXX-XXXX or visit the nearest brach at http://vwxyzcom/branches",
 "\\n', 'To apply for a new credit card, please visit http://vwxyzcom/credit-card/apply or call The VWXYZ Bank 24-Hour Customer Care Centre at 1800-XXX-XXXX or visit the nearest brach at http://vwxyzcom/branches",
 "\\n', 'To apply for a new credit card, please visit http://vwxyzcom/credit-card/apply or call The VWXYZ Bank 24-Hour Customer Care Centre at 1800-XXX-XXXX or visit the nearest brach at http://vwxyzcom/branches",
 "\\n', 'Below documents are required for applying for a new credit card: 1)Identitiy proof - PAN Card, Passport, Voter, Aadhar 2) Address Proof - Driving License, Electricity Bill, Aadhar Card 3) passport size photograph",
 "\\n', 'Below documents are required for applying for a new credit card: 1)Identitiy proof - PAN Card, Passport, Voter, Aadhar 2) Address 

In [8]:
type(sent_tokens)

list

In [9]:
sent_tokens[0]

"['To apply for a new credit card, please visit http://vwxyzcom/credit-card/apply or call The VWXYZ Bank 24-Hour Customer Care Centre at 1800-XXX-XXXX or visit the nearest brach at http://vwxyzcom/branches"

In [10]:
import nltk
import string
import random

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
from sklearn.metrics.pairwise import cosine_similarity

In [13]:
#LEMMATIZATION
lemmer = nltk.stem.WordNetLemmatizer()
def LemTokens(tokens):
    return [lemmer.lemmatize(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)
#NORMALIZE
def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

In [14]:
GREETING_INPUTS = ("hello", "hi", "greetings", "hi bot", "hey", "how are you", "good morning")
GREETING_RESPONSES = ["hi", "hey", "hello"]

In [15]:
def greeting(sentence):
 
    for word in sentence.split():
        if word.lower() in GREETING_INPUTS:
            return random.choice(GREETING_RESPONSES)

In [16]:
def response(user_response):
    robo_response=''
    sent_tokens.append(user_response)
    TfidfVec = TfidfVectorizer(tokenizer=LemNormalize, stop_words='english')
    tfidf = TfidfVec.fit_transform(sent_tokens)
    vals = cosine_similarity(tfidf[-1], tfidf)
    idx=vals.argsort()[0][-2]
    flat = vals.flatten()
    flat.sort()
    req_tfidf = flat[-2]
    if(req_tfidf<0.2):
        robo_response=robo_response+"I am sorry I don't understand you. Can you reach out to the customer care instead 1800-XXX-XXX"
        return robo_response
    else:
        robo_response = sent_tokens[idx]
        return robo_response

In [17]:
flag=True
print("BOT: Hi I am Emilia! I will answer your queries about services - Credit Card, Savings Account. If you want to exit, type Bye!")
while(flag==True):
    user_response = input()
    user_response=user_response.lower()
    if(user_response!='bye'):
        if(user_response=='thanks' or user_response=='thank you' ):
            flag=False
            print("BOT: You are welcome..")
        else:
            if(greeting(user_response)!=None):
                print("BOT: "+greeting(user_response))
            else:
                print("BOT: ",end="")
                print(response(user_response))
                sent_tokens.remove(user_response)
    else:
        flag=False
        print("BOT: Great! Have a nice day.")

BOT: Hi I am Emilia! I will answer your queries about services - Credit Card, Savings Account. If you want to exit, type Bye!
Hi
BOT: hello
I want a new credit card
BOT: 

C:\Anaconda Installations\AC\lib\site-packages\sklearn\feature_extraction\text.py:301: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'u', 'wa'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


['To apply for a new credit card, please visit http://vwxyzcom/credit-card/apply or call The VWXYZ Bank 24-Hour Customer Care Centre at 1800-XXX-XXXX or visit the nearest brach at http://vwxyzcom/branches
What are the best credit cards
BOT: I am sorry I don't understand you. Can you reach out to the customer care instead 1800-XXX-XXX
Bye
BOT: Great! Have a nice day.


In [80]:
flag=True
print("BOT: Hi I am Emilia! I will answer your queries about services - Credit Card, Savings Account. If you want to exit, type Bye!")
while(flag==True):
    user_response = input()
    user_response=user_response.lower()
    if(user_response!='bye'):
        if(user_response=='thanks' or user_response=='thank you' ):
            flag=False
            print("BOT: You are welcome..")
        else:
            if(greeting(user_response)!=None):
                print("BOT: "+greeting(user_response))
            else:
                print("BOT: ",end="")
                print(response(user_response))
                sent_tokens.remove(user_response)
    else:
        flag=False
        print("BOT: Great! Have a nice day.")

BOT: Hi I am Emilia! I will answer your queries about services - Credit Card, Savings Account. If you want to exit, type Bye!
Hello
BOT: hey
Can you book movie tickets?
BOT: I am sorry I don't understand you. Can you reach out to the customer care instead 1800-XXX-XXX
can you track the status of the last order?
BOT: I am sorry I don't understand you. Can you reach out to the customer care instead 1800-XXX-XXX
Bye
BOT: Great! Have a nice day.


In [93]:
flag=True
print("BOT: Hi I am Emilia! I will answer your queries about services - Credit Card, Savings Account. If you want to exit, type Bye!")
while(flag==True):
    user_response = input()
    user_response=user_response.lower()
    if(user_response!='bye'):
        if(user_response=='thanks' or user_response=='thank you' ):
            flag=False
            print("BOT: You are welcome..")
        else:
            if(greeting(user_response)!=None):
                print("BOT: "+greeting(user_response))
            else:
                print("BOT: ",end="")
                print(response(user_response))
                sent_tokens.remove(user_response)
    else:
        flag=False
        print("BOT: Great! Have a nice day.")

BOT: Hi I am Emilia! I will answer your queries about services - Credit Card, Savings Account. If you want to exit, type Bye!
hello
BOT: hello
I want to redeem my pay back points
BOT: \n', 'The Card Member can redeem his/ her accumulated VWXYZ Bank Reward Points against\n', 'redemption offers made by VWXYZ Bank from time to time through net banking - wwwVWXYZbankcom
How can I update aadhar card details?
BOT: \n', 'Customer can update Aadhar Card details through net banking or by visiting the nearest branch
can you track the status of the last order?
BOT: I am sorry I don't understand you. Can you reach out to the customer care instead 1800-XXX-XXX
Bye
BOT: Great! Have a nice day.


In [94]:
flag=True
print("BOT: Hi I am Emilia! I will answer your queries about services - Credit Card, Savings Account. If you want to exit, type Bye!")
while(flag==True):
    user_response = input()
    user_response=user_response.lower()
    if(user_response!='bye'):
        if(user_response=='thanks' or user_response=='thank you' ):
            flag=False
            print("BOT: You are welcome..")
        else:
            if(greeting(user_response)!=None):
                print("BOT: "+greeting(user_response))
            else:
                print("BOT: ",end="")
                print(response(user_response))
                sent_tokens.remove(user_response)
    else:
        flag=False
        print("BOT: Great! Have a nice day.")

BOT: Hi I am Emilia! I will answer your queries about services - Credit Card, Savings Account. If you want to exit, type Bye!
hello
BOT: hello
Can you book movie tickets?
BOT: \n', 'Yes, VWXYZ card can be used to book a ticket with railways; However, when a railway ticket is booked with a Credit Card, the Card Member will have to pay for the purchase of\n', 'the ticket subject to any additional charges, if applicable
Bye
BOT: Great! Have a nice day.
